define j = Character("JinAxel")
define hib = Character("Hibiki", image="hib")
define kom = Character("Komugi", image="kom")
define noe = Character("Noel", image="noe")
define yuk = Character("Yukari", image="yuk")
define miz = Character("Mizuki", image="miz")
define shi = Character("Shiina", image="shi")
define rit = Character("Ritsu", image="rit")
define hon = Character("Honoka", image="hon")
define kur = Character("Kuriko", image="kur")
define miy = Character("Miyu", image="miy")
define mar = Character("Marine", image="mar")
define hik = Character("Hikari", image="hik")
define aka = Character("Akane", image="aka")
define chi = Character("Chika", image="chi")
define wen = Character("Wenbeez", image="wen")
define yum = Character("Yumemi", image="yum")
define dayt = Character("Daytona")
define gsyuk = Character("Regis Philbin")
define gm = Character("Game Master")